title: FreeEMS Puma Spin 1 How-To
header:
  - links
  - prev_next
footer:
  - prev_next
  - footer
structure:
  - index:
    - intro # introductionary chapter
    - index # index (not used yet)
    - pcb_overview # overview of the board
  - materials:
    - using_bom # BOM configuration chapter
    - sourcing_components # chapter guiding how to order components
  - general_info:  
    - assembly_tools 
  - assembly_mod:
    - assembly_essential_mods # Spin1-specific modifications 
  - assembly_SMDpartA: 
    - assembly_overview # assembly introduction chapter
    - assembly1_primary
  - assembly_SMDpartB:
    - assembly2_brv
    - assembly3_map
    - assembly4_aap
    - assembly5_rpm
    - assembly6_fuel
    - assembly7_cht
    - assembly8_mat
    - assembly9_iat
    - assembly10_tps
  - assembly_SMDpartC:
    - assembly11_injection
    - assembly12_ignition
  - reflow:
    - pcb_bake # instructions how to bake the board in an oven
  - assembly_through_hole:
    - assembly13_after_reflow
    - ignition_th
    - ign_pullup_mod
    - injection_th
    - temp_portT_mod
    - usb_pnp_mod
  - serial_monitor:
    - sm_install # how to load the serial monitor using BDM
  - firmware:
    - firmware_upload # how to upload the FreeEMS firmware to the board
  - testing_inputs:
    - testing_inputs
  - testing_outputs:
    - testing_outputs
  - installation:
    - installation # how to install your Puma Spin 1 board
